### ISSUE TITLE
How can I get access? 

### ISSUE THREAD

**Issue by samuelbeek** [WhiskeyProject/whiskey-api#1]
Is there anywhere I can request an API-key for this product? Or do I have to fork and run it myself? 

Cheers

**Comment by AaronScruggs** [comment]
Hi samuelbeek, you can make GET requests without any auth. Take a look at https://evening-citadel-85778.herokuapp.com/whiskey/ for a list of whiskies. https://evening-citadel-85778.herokuapp.com/docs/ documents all of the other endpoints. The (poorly named) /shoot/ endpoint is for filtering and ranking by attributes.

**Comment by samuelbeek** [comment]
thanks a  lot :)
